on: [push]

name: year increament counter

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Print changed files
      run: |
        git fetch
        STR=$(git diff --name-only HEAD^ HEAD)
        year=$(echo "$STR" | grep -oE "[0-9]{4}" | head -n 1)
        day=$(echo "$STR" | grep -oE "day_[0-9]{2}" | head -n 1)
        if [ -z "$year" ] || [ -z "$day" ]; then
            exit 1
        fi
